version: '3.7'

services:

   
  producer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    tty: true
    networks:
      - backend
      
  
networks:
  backend: